### ISSUE TITLE
can't retrieving stream information

### ISSUE THREAD

**Issue by cloudpaijo** [NewsGuyTor/IPTVChecker#1]
Hi, 
am just tried some source playlist w/  & w/o Increase output verbosity. 
ffmpeg and ffprobe already installed and correct Path.

the issue is can't retrieving Audio Video stream information,below the result :  
←[91m10/41 ICE| BESTA DEILDIN 2 FHD - Alive: ✕ ||| Video: Unknown - Audio: Unknown←[0m
2024-08-19 17:24:51,076 - INFO - 10/41 ICE| BESTA DEILDIN 2 FHD - Alive: ✕ ||| Video: Unknown - Audio: Unknown

am checking on folder captures screenshots is blank and  there is no output file

am looking forward to your reply
Thanks & Regards,
Paijo

**Comment by NewsGuyTor** [comment]
2 should be solved now, sorry for that oversight. 

Try again with the updated script. 

If that doesn't solve 1, then copy the relevant line from the playlist into here (make sure to anonymize it and remove passwords etc).

**Comment by cloudpaijo** [comment]
OK now its working properly.
also I modified it myself by inserting it  line 134. >= 4096 for 4K resolution and >= 3840 for UHD.
Thank You.
