### ISSUE TITLE
there is no printing result saving into a new .txt or .m3u

### ISSUE THREAD

**Issue by cloudpaijo** [NewsGuyTor/IPTVChecker#2]
i have some issue and feedback about this :

1. there is no printing output result on the console saving into a new .txt or .m3u (separate Alivestream_result.m3u & failedstream_result .m3u)
2. the output is saved into a new m3u with additional Video and Audio stream information on channel e.g. SKY NEWS 1080p25 H264 | 192 kbps AAC .This will be very useful to compare of picture and audio quality from various file streaming sources.

this is nice repo. very useful and easy to use for non programmer like me
hope there is an update for this features
Thanks a lot

**Comment by NewsGuyTor** [comment]
Great suggestions!

Both has been added now. Try it, with -split and -rename :)

**Comment by cloudpaijo** [comment]
> Great suggestions!
> 
> Both has been added now. Try it, with -split and -rename :)

1. rename channel incl AV information only work with split method. rename channel without split is not work.
2. i found minor bug, result of renamed channel the title does not match while playing on player/VLC, what is shown on the player is audio title. am removing "dash" symbol  on line 324 {video_info.split()[-1]}  {audio_info} , and it work.

else is OK, Thanks & Great Job !

![tittle](https://github.com/user-attachments/assets/7b311bce-d199-4614-8d31-fa3c4c1ebec1)

**Comment by NewsGuyTor** [comment]
Should be fixed now
